name: Colour Conversion Build

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: build
        run: gcc -o colour colour.c hex_to_rgb.c rgb_to_hex.c help.c

      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: colour
          path: ./colour